### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
To get you started, see #3

### CODE REVIEW

**Comment by IzzySoft** [comment]
@roeiedri will this be merged? I'm about to drop my fork for cleanup.

**Comment by roeiedri** [comment]
In the future yes

**Comment by IzzySoft** [comment]
Which future? What are you waiting for if I might ask? This PR doesn't conflict with anything (except for the README.md which you seem to have added here). Just the opposite, it would help your listing with my repo already now, as you could keep the description up-to-date and maybe even add per-release changelogs.

**Comment by roeiedri** [comment]
Ill have to ask to remove changes to readme, leave only added files

**Comment by IzzySoft** [comment]
@roeiedri please take a look at the commits: those changes to the Readme were added by you it seems. I usually do not touch anything outside of `fastlane/*` when providing initial structures. I just rebased and force-pushed, looks like that solved it.

No idea how your commits got in here in the first place, though; could you please merge before something similar happens again? :zany_face: Feel free to squash.

**Comment by IzzySoft** [comment]
Thanks! Adjusted YML metadata in my repo to follow your future updates in Fastlane as well (summary, description, icon, featureGraphic; should you add other elements like screenshots, just let me know).

**Comment by roeiedri** [comment]
Yeah sorry of the long wait😅
Whar do we do from here?

**Comment by IzzySoft** [comment]
For F-Droid.org? Waiting for the next release to be tagged (so we have Fastlane at the tag). I've already [left a note](https://gitlab.com/fdroid/rfp/-/issues/1285#note_550091912) on the corresponding RFP to keep it from being closed (it would have been marked for closure this week otherwise, due to inactivity). You're welcome to chime in there – or let me know when the tag is ready so I report it back.

**Comment by IzzySoft** [comment]
@roeiedri I just wonder why this cannot be found at the [`1.0.7` tag](https://github.com/Chooloo/koler/tree/v1.0.7) published 8 days ago? We're waiting for Fastlane to become available at a tag for F-Droid inclusion [here](https://gitlab.com/fdroid/rfp/-/issues/1285). It's not available at [tag `1.0.6`](https://github.com/Chooloo/koler/tree/1.0.6) either, which was also created after this PR was merged. Anything wrong?

**Comment by roeiedri** [comment]
@IzzySoft i want to get this issue done
Tell me what to do and ill finish with it asap.
Now fr :)

**Comment by IzzySoft** [comment]
I have no idea what branch you tag (looks like `dev` is the one). The next tag on master should have it. Or you need to merge the changes from master to dev if you want to continue tagging there. Whichever it is: you need to have fastlane in the branch your tag is based on.

**Pull request merged**
