### PR TITLE
Group recent calls

### LINKED ISSUE #395: Recents number repeated
## Checklist

- [x] I am using the latest version - 1.4.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

-->

### Actual behaviour

Show all call details in history not separately.

### Screenshots/Screen recordings

Screenshot_20220331-230541_1

### Device info
 - Android version/Custom ROM version:10
 - Device model:in1

### PR DESCRIPTION
**Pull request by vbh**
Closes #395, #207
Groups the recent calls and shows individual call history in show history screen

### CODE REVIEW

**Comment by roeiedri** [comment]
Could you please send a screenshot of the feature?

**Comment by vbh** [comment]
> Could you please send a screenshot of the feature?

Added

**Comment by Ilithy** [comment]
Is it possible to make it an option? Some users like the current behavior, thank you very much

**Review by roeiedri — APPROVED** [review]
Nice job! Thanks :)

**Pull request merged**
