### PR TITLE
Fixed an issue where statusbar icons where not visible in light mode (Android 12)

### PR DESCRIPTION
**Pull request by Esarve**
A added a fix which fixes statusbar for both light and dark mode. Screenshot for before and after the fix is attached below

before:
qemu-system-x86_64_0GFtauEWVC

after:
qemu-system-x86_64_Brm6R4H6fl

### CODE REVIEW

**Review by roeiedri — APPROVED** [review]
Thanks!

**Comment by roeiedri** [comment]
After running with the code you added, the notification bar isn't transparent, it's slightly darker than the app's background

**Comment by roeiedri** [comment]
nvm fixed it :)

**Comment by roeiedri** [comment]
The change you added makes status bar be white in dark theme as well, can you take a look at that?

**Comment by Esarve** [comment]
> The change you added makes status bar be white in dark theme as well, can you take a look at that?

Yes with the current stagging branch, the status bar stays white in dark mode. 
But I've checked now with the code I used for the PR and it works as expected (dark statusbar in dark mode)
It seems something might have happened when you moved the code in _ColorsInteractor_ . I am looking into it

**Comment by Esarve** [comment]
My initial findings are these:

- In `windowColor ` in `ColorsInteractorImpl` class always returning -1. That's why statusbar is not changing in dark mode.
- in `ColorsInteractorImpl` class, the application context is being used. But I think we need the activity / activity context to get the window color for that specific activity as activates can have different window color in the same app due to themes. That's why -1 is being returned everytime since the context is not an activity.  That same code works in the base activity.

**Comment by Esarve** [comment]
@roeiedri Any update on this issue? I mean should we move the code back to the activity? or keep it as it is

**Comment by elesto** [comment]
Im using dark mode and the status bar is white and I cant read anything. Using version 1.4.5

**Pull request merged**
