### PR TITLE
fix: repetitive text while searching

### PR DESCRIPTION
**Pull request by vbh**
While searching for contacts in the search bar, characters keep getting repeated.

https://user-images.githubusercontent.com/56578479/159303739-c1e5a9a5-d745-4f84-9e93-4a5b1a14f163.mp4

### CODE REVIEW

**Comment by sonalder-darlene** [comment]
I hope this will soon being review and merged, this bug makes the app almost unusable

**Review by roeiedri — CHANGES_REQUESTED** [review]
The input filter you changed always return either null or an empty string (" ")
If thats not a mistake pls explain :)

**Comment by vbh** [comment]
Every time a character is inserted `InputFilter`  is called and if the character is not acceptable then that it can be replaced, which in our case is empty string because if the character is anything apart from letters or digits then it should be skipped or else keep the original text by returning null

From [documentation.](https://developer.android.com/reference/android/text/InputFilter#filter(java.lang.CharSequence,%20int,%20int,%20android.text.Spanned,%20int,%20int))
> Return the CharSequence that you would like to have placed there instead, including an empty string if appropriate, or null to accept the original replacement.

**Comment by roeiedri** [comment]
Ohhhhhh ok so i was wrong with the way i was using the Input Filter.
Thanks!

**Comment by roeiedri** [comment]
Thanks!

**Pull request merged**
